### ISSUE TITLE
Can't jump to next placeholder

### ISSUE THREAD

**Issue by aldevv** [srydell/vim-template#1]
after the snippet expands, i can't jump to the next placeholder.

i use `<a-t>` to both expand and to jump to the next placeholder

**Comment by srydell** [comment]
Hi!

Yes, UltiSnips did some change about a year ago to fix something unrelated, and unfortunately that broke the jump to placeholder after expanding on new file. I opened a pr there (https://github.com/SirVer/ultisnips/pull/1148) but I didn't have the time to close it at the moment. The way I see it, you could fork the UltiSnips repo, apply the patch and use that. Or you could make a new pr there.

Hope that helps!

**Comment by aldevv** [comment]
i was loosing my mind over this lol

thanks!
